//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QuranTranslationImageGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("QuranTranslationImageGenerator.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|Im Namen Allahs, des Allerbarmers, des Barmherzigen!
        ///1|2|Alles Lob gebührt Allah, dem Herrn der Welten
        ///1|3|dem Allerbarmer, dem Barmherzigen
        ///1|4|dem Herrscher am Tage des Gerichts!
        ///1|5|Dir (allein) dienen wir, und Dich (allein) bitten wir um Hilfe.
        ///1|6|Führe uns den geraden Weg
        ///1|7|den Weg derer, denen Du Gnade erwiesen hast, nicht (den Weg) derer, die(Deinen) Zorn erregt haben, und nicht (den Weg) der Irregehenden.
        ///2|1|Alif Lam Mim.
        ///2|2|Dies ist (ganz gewiß) das Buch (Allahs), das keinen Anlaß zum Zwei [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string de_aburida {
            get {
                return ResourceManager.GetString("de_aburida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|In the name of Allah, the Entirely Merciful, the Especially Merciful.
        ///1|2|[All] praise is [due] to Allah, Lord of the worlds -
        ///1|3|The Entirely Merciful, the Especially Merciful,
        ///1|4|Sovereign of the Day of Recompense.
        ///1|5|It is You we worship and You we ask for help.
        ///1|6|Guide us to the straight path -
        ///1|7|The path of those upon whom You have bestowed favor, not of those who have evoked [Your] anger or of those who are astray.
        ///2|1|Alif, Lam, Meem.
        ///2|2|This is the Book about which there is no doubt, a g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string en_sahih {
            get {
                return ResourceManager.GetString("en.sahih", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|به ناوی خوای به‌خشنده‌ی میهره‌بان (به ناوی ئه‌و خوایه‌ی كانگای ڕه‌حمه‌ت و سۆزو به‌زه‌ییه‌).
        ///1|2|‌سوپاس و ستایش هه‌ر شایسته‌ی خوایه و بۆ خوایه‌، که خاوه‌ن و په‌روه‌ردگاری هه‌موو جیهانیان و هه‌موو بوونه‌وه‌ره.
        ///1|3|به‌خشنده‌ی میهره‌بان‌، کانگای ڕه‌حمه‌ت و میهره‌بانیه (ڕه‌حمه‌تی له دنیادا هه‌موو شتێکی گرتۆته‌وه‌، به‌ڵام له قیامه‌تدا ته‌نها بۆ ئیماندارانه‌).
        ///1|4|خاوه‌ن و سه‌رداری ڕۆژی پاداشت و سزایه (پادشای ڕۆژی قیامه‌ته که دادپه‌روه‌ری ڕه‌هاو بێ سنووری تێدا به‌رپا ده‌کات).
        ///1|5|خوایه‌، ته‌نها هه‌ر تۆ ده‌په‌ر [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ku_asan {
            get {
                return ResourceManager.GetString("ku.asan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|بِسْمِ اللَّهِ الرَّحْمَـٰنِ الرَّحِيمِ
        ///1|2|الْحَمْدُ لِلَّهِ رَبِّ الْعَالَمِينَ
        ///1|3|الرَّحْمَـٰنِ الرَّحِيمِ
        ///1|4|مَالِكِ يَوْمِ الدِّينِ
        ///1|5|إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
        ///1|6|اهْدِنَا الصِّرَاطَ الْمُسْتَقِيمَ
        ///1|7|صِرَاطَ الَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ الْمَغْضُوبِ عَلَيْهِمْ وَلَا الضَّالِّينَ
        ///2|1|بِسْمِ اللَّهِ الرَّحْمَـٰنِ الرَّحِيمِ الم
        ///2|2|ذَٰلِكَ الْكِتَابُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ
        ///2|3|الَّذِينَ يُؤْمِنُونَ بِالْغَيْبِ وَيُقِيمُونَ الصَّلَاةَ وَمِمَّا رَزَقْ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quran_simple {
            get {
                return ResourceManager.GetString("quran-simple", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ
        ///1|2|ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ
        ///1|3|ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ
        ///1|4|مَـٰلِكِ يَوْمِ ٱلدِّينِ
        ///1|5|إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
        ///1|6|ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ
        ///1|7|صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ
        ///2|1|بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ الٓمٓ
        ///2|2|ذَٰلِكَ ٱلْكِتَـٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًى لِّلْمُتَّقِينَ
        ///2|3|ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّا [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quran_uthmani {
            get {
                return ResourceManager.GetString("quran_uthmani", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ
        ///1|2|ٱلْحَمْدُ لِلَّهِ رَبِّ ٱلْعَـٰلَمِينَ
        ///1|3|ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ
        ///1|4|مَـٰلِكِ يَوْمِ ٱلدِّينِ
        ///1|5|إِيَّاكَ نَعْبُدُ وَإِيَّاكَ نَسْتَعِينُ
        ///1|6|ٱهْدِنَا ٱلصِّرَٰطَ ٱلْمُسْتَقِيمَ
        ///1|7|صِرَٰطَ ٱلَّذِينَ أَنْعَمْتَ عَلَيْهِمْ غَيْرِ ٱلْمَغْضُوبِ عَلَيْهِمْ وَلَا ٱلضَّآلِّينَ
        ///2|1|بِسْمِ ٱللَّهِ ٱلرَّحْمَـٰنِ ٱلرَّحِيمِ الٓمٓ
        ///2|2|ذَٰلِكَ ٱلْكِتَـٰبُ لَا رَيْبَ ۛ فِيهِ ۛ هُدًۭى لِّلْمُتَّقِينَ
        ///2|3|ٱلَّذِينَ يُؤْمِنُونَ بِٱلْغَيْبِ وَيُقِيمُونَ ٱلصَّلَوٰةَ وَمِمَّ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quran_uthmani_me_quran {
            get {
                return ResourceManager.GetString("quran_uthmani_me_quran", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1|1|بِسمِ اللَّهِ الرَّحمـٰنِ الرَّحيمِ
        ///1|2|الحَمدُ لِلَّهِ رَبِّ العـٰلَمينَ
        ///1|3|الرَّحمـٰنِ الرَّحيمِ
        ///1|4|مـٰلِكِ يَومِ الدّينِ
        ///1|5|إِيّاكَ نَعبُدُ وَإِيّاكَ نَستَعينُ
        ///1|6|اهدِنَا الصِّرٰطَ المُستَقيمَ
        ///1|7|صِرٰطَ الَّذينَ أَنعَمتَ عَلَيهِم غَيرِ المَغضوبِ عَلَيهِم وَلَا الضّالّينَ
        ///2|1|بِسمِ اللَّهِ الرَّحمـٰنِ الرَّحيمِ الم
        ///2|2|ذٰلِكَ الكِتـٰبُ لا رَيبَ ۛ فيهِ ۛ هُدًى لِلمُتَّقينَ
        ///2|3|الَّذينَ يُؤمِنونَ بِالغَيبِ وَيُقيمونَ الصَّلوٰةَ وَمِمّا رَزَقنـٰهُم يُنفِقونَ
        ///2|4|وَالَّذينَ يُؤمِنونَ بِما أُنزِلَ إِل [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string quran_uthmani_min {
            get {
                return ResourceManager.GetString("quran_uthmani_min", resourceCulture);
            }
        }
    }
}
